# Configuration for pytest
[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra --ignore=data/"
testpaths = [
    "tests",
]

# Configuration for Black, the Python code formatter
[tool.black]
target-version = ["py311"]
# line-length = 130
exclude = '''
/(
    data
  | .venv
  | .*\.ipynb$
)/
'''

# Configuration for Pylint
[tool.pylint."MESSAGES CONTROL"]
disable = [
    "missing-module-docstring",
    "missing-function-docstring",
    "missing-class-docstring",
    "too-many-arguments",
    "too-many-positional-arguments",
    "use-dict-literal"
]
max-line-length = 130
