name: "Test"
on:
  pull_request:
    branches:
      - "*"

env:
  PYTHON_VERSION: "3.12"

permissions:
  actions: "read"

jobs:
  unit-test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: "run unit tests"
        run: "make unit-test"

      - name: "run integration tests"
        run: "make integration-test"